version: '2'
services:
  odoo:
    build: .
    image: img_odoo_12
    container_name: cont_odoo_12-proy1
    depends_on:
      - db
    volumes:
      - "data-odoo:/filestore"
      - "./src:/opt/odoo"
    environment:
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_DB_HOST=db
      - ODOO_ADMIN_PASSWORD=randompass
    ports:
      - "8069:8069"
      - "8072:8069"
    restart: always
    command: "/opt/odoo/odoo-bin -c /opt/odoo/.odoorc"
    #command: "/opt/odoo/odoo-bin -c /opt/odoo/.odoorc -d odoodb -i base"
    #command: "tail -f /dev/null"
    networks: 
      - red-odoo12-db
  db:
    image: postgres:9.6
    container_name: cont_db_12-proy1
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres      
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
    volumes:
      - "data-db:/var/lib/postgresql/data"
    restart: always
    networks: 
      - red-odoo12-db
      
networks:
   red-odoo12-db:
  
volumes:
  data-odoo:
  data-db:
